### ISSUE TITLE
[Feat] 검색시 가수도 동시에 검색되도록 하기❗️

### ISSUE THREAD

**Issue by dahae0320** [ProjectInTheClass/GasaOK#48]
## Feature Issue
SearchVC에서 가수 검색도 가능하도록 하기

## ToDo(Task)
- [x] 기존의 코드 파악 (제목 검색, 검색 내용을 어떻게 뿌려주는지 확인)
- [x] 필요없는 코드 삭제❗️
- [x] 가수 검색 `URLSesseion` 코드 짜기
- [x] playground에서 위 코드로 `API 통신`이 잘 되는지 확인
- [x] 가수 검색 결과와 제목 검색 결과를 어떻게 뿌려줄 것인지 로직짜기 (짜고나면 코멘트에 작성)
- [x] 기존의 제목 검색 `URLSession` 코드 수정
- [x] 실제 검색 기능에 추가
- [x] 콘솔에 찍어서 제목 검색과 노래 검색이 동시에 잘 출력되는지 확인
