### ISSUE TITLE
[Reject] 가사 저작권 이슈

### ISSUE THREAD

**Issue by leeyi1203** [ProjectInTheClass/GasaOK#63]
### Reject Issue
가사 저작권 이슈로 앱 내에서 바로 보여줄 수 없음

### Solution
앱 내에 가사를 바로 뿌려줄 수 없는 경우 API 사용 불필요, 링크만 연결되도록 하자!

### ToDo(Task)
- [x] song detail 화면 삭제
- [x] lyrics API 삭제
- [x] SearchVC, 보관함VC : table view cell 클릭 시 알림창 띄우기 (가사를 보러 가시겠습니까?)
- [x] 알림창에서 이동 클릭 시 네이버 검색 결과 링크로 연결
