### ISSUE TITLE
[Refactoring] 리팩토링2 - 다혜

### ISSUE THREAD

**Issue by dahae0320** [ProjectInTheClass/GasaOK#78]
## Feature Issue
리팩토링 두번째! 코드를 깔끔하게 만들어보자. 여러 뷰컨에서 사용하는 Alert는 클래스로 빼서 공동으로 사용할 수 있도록 하자.

## ToDo
- [x] Alert 함수 Class로 빼내기
- [x] if-else 문은 switch 문으로 바꾸기
- [x] 반복되는 코드는 함수화하여 효율적으로 만들기
