### ISSUE TITLE
[Feat] '가사오케' 다음 릴리즈

### ISSUE THREAD

**Issue by dahae0320** [ProjectInTheClass/GasaOK#80]
## Feature Issue
'가사오케'의 다음 릴리즈 회의가 9월 13일 진행됩니다.

## ToDo
- [ ] 새로 추가할 기능 논의하기
- [ ] 가사오케 새로운 디자인
- [ ] 보관함 갯수 늘리기
