### ISSUE TITLE
[View] left button + searchbar in SearchView

### ISSUE THREAD

**Issue by dahae0320** [ProjectInTheClass/GasaOK#82]
## View Issue
<img src="https://user-images.githubusercontent.com/50159740/194801674-94a2c3d9-a9d7-4cbf-93d1-5e4ff4ad1369.png" height=400>

위 사진에서 상단에 위치한 검색바와 왼쪽 버튼을 구현하려고 한다. 기존의 SearchController를 커스텀하거나 SearchBar로 바꾸어야 한다.
UISearchController로 searchBar의 크기 조절이 쉽지 않아서 UISearhBar로 바꿀 것이다.

## ToDo
- [x] UISearchController 코드 주석 처리하기
- [x] Storyboard에서 SearchBar, Button 넣기
- [x] Delegate 설정하기
- [x] Cancel 버튼 설정하기
